@startuml
interface InvoiceFormatterFactory
class DefaultInvoiceFormatterFactory implements InvoiceFormatterFactory
class MockInvoiceFormatterFactory implements InvoiceFormatterFactory

class DefaultInvoiceFormatter implements InvoiceFormatter

DefaultInvoiceFormatterFactory ..> DefaultInvoiceFormatter


class InvoiceFormatterFactory{
 +createInvoiceFormatter(): InvoiceFormatter
}
class DefaultInvoiceFormatterFactory {
 +createInvoiceFormatter(): InvoiceFormatter
}
class MockInvoiceFormatterFactory {
 +createInvoiceFormatter(): InvoiceFormatter
}
@enduml